// sentences.js — Sentence templates and assembly logic
// Extracted from categories.js (Phase 3 refactoring)

import { lang, cardinalToWords, pick } from './number-utils.js';

// ── Ukrainian noun declension helper (for cardinal noun agreement) ─────────

/**
 * Determine declension case for Ukrainian number-noun agreement.
 * @param {number} n
 * @returns {number} 1 (singular), 2 (paucal 2-4), or 5 (plural 5+)
 */
export function ukDeclensionCase(n) {
  const abs = Math.abs(n);
  const lastTwo = abs % 100;
  const lastOne = abs % 10;
  if (lastTwo >= 11 && lastTwo <= 19) return 5;
  if (lastOne === 1) return 1;
  if (lastOne >= 2 && lastOne <= 4) return 2;
  return 5;
}

// ── Sentence templates per category (language-dependent) ───────────────────

const SENTENCES = {
  en: {
    cardinals: [
      "The answer is {V}.",
      "Please go to room {V}.",
      "The class has {V} {student|students}.",
      "I need {V} {copy|copies} of this document.",
      "The bus number is {V}.",
      "She scored {V} {point|points} on the test.",
      "We have {V} {ticket|tickets} left.",
      "Turn to page {V} in your textbook.",
      "He ran {V} {mile|miles} this morning.",
      "Your order number is {V}.",
      "The room has {V} {chair|chairs}.",
      "She waited {V} {minute|minutes}.",
      "The building has {V} {floor|floors}.",
      "We need {V} more {volunteer|volunteers}.",
      "I counted {V} {bird|birds} in the tree.",
    ],
    ordinals: [
      "He finished in {V} place.",
      "This is the {V} time I've asked.",
      "She lives on the {V} floor.",
      "It's his {V} birthday today.",
      "We're celebrating our {V} anniversary.",
      "Take the {V} turning on the left.",
      "She came {V} in the race.",
      "This is the {V} edition of the book.",
      "It's the {V} day of the month.",
      "Read the {V} chapter carefully.",
      "He was the {V} person to arrive.",
      "Our team finished in {V} place.",
      "It was her {V} attempt.",
      "The {V} question was the hardest.",
      "This is my {V} visit to this city.",
    ],
    years: [
      "She was born in {V}.",
      "The event took place in {V}.",
      "This building was constructed in {V}.",
      "He graduated in {V}.",
      "The company was founded in {V}.",
      "The album was released in {V}.",
      "That law was passed in {V}.",
      "The discovery was made in {V}.",
      "My parents got married in {V}.",
      "The film came out in {V}.",
      "The first edition was printed in {V}.",
      "We moved to this city in {V}.",
      "The bridge was opened in {V}.",
      "That photograph was taken in {V}.",
      "The tradition started in {V}.",
    ],
    decades: [
      "That happened in {V}.",
      "The style was popular in {V}.",
      "Music was different in {V}.",
      "They grew up in {V}.",
      "Fashion changed a lot in {V}.",
      "It was a common trend in {V}.",
      "Technology changed rapidly in {V}.",
      "Many great films were made in {V}.",
      "People dressed differently in {V}.",
      "That song reminds me of {V}.",
      "The economy was strong in {V}.",
      "Cars looked very different in {V}.",
      "Television was huge in {V}.",
      "Life was simpler in {V}.",
      "My parents met in {V}.",
    ],
    fractions: [
      "Add {V} of a cup of flour.",
      "About {V} of the students passed.",
      "The tank is {V} full.",
      "Mix {V} of the ingredients.",
      "Roughly {V} of the population agreed.",
      "Cut it into pieces and take {V}.",
      "We've completed {V} of the project.",
      "Only {V} of the seats are taken.",
      "She ate {V} of the pizza.",
      "About {V} of the budget was spent.",
      "The bottle is {V} empty.",
      "He read {V} of the book last night.",
      "They finished {V} of the work by noon.",
      "Roughly {V} of the land is forest.",
      "We used {V} of the available space.",
    ],
    decimals: [
      "The measurement was {V} centimeters.",
      "It weighs {V} kilograms.",
      "The result is {V}.",
      "The reading shows {V}.",
      "The average is {V}.",
      "The pH level is {V}.",
      "The distance is {V} meters.",
      "The temperature was {V} degrees.",
      "The speed reached {V} kilometers per hour.",
      "The sample measured {V} grams.",
      "The voltage is {V} volts.",
      "The height is {V} meters.",
      "The ratio was {V} to one.",
      "The concentration is {V} milligrams.",
      "The thickness is {V} millimeters.",
    ],
    currencies: [
      "The total comes to {V}.",
      "That will be {V} please.",
      "Your change is {V}.",
      "The price is {V}.",
      "I paid {V} for it.",
      "It costs {V} per unit.",
      "The bill came to {V}.",
      "She spent {V} on groceries.",
      "The ticket price is {V}.",
      "We saved {V} this month.",
      "The repair will cost {V}.",
      "He donated {V} to charity.",
      "The rent is {V} per month.",
      "Your balance is {V}.",
      "The delivery fee is {V}.",
    ],
    percentages: [
      "The interest rate is {V}.",
      "About {V} of people agreed.",
      "Sales increased by {V}.",
      "The humidity is {V}.",
      "There's a {V} chance of rain.",
      "The score improved by {V}.",
      "The battery is at {V}.",
      "Unemployment dropped by {V}.",
      "The project is {V} complete.",
      "Voter turnout was {V}.",
      "The discount is {V} off.",
      "Prices went up by {V}.",
      "The success rate is {V}.",
      "Attendance reached {V} today.",
      "The tax rate is {V}.",
    ],
    roomBus: [
      "Please go to {V}.",
      "You need to take {V}.",
      "I'm looking for {V}.",
      "Can you tell me where {V} is?",
      "Do you know where {V} is?",
      "{V} should be nearby.",
      "I was told to go to {V}.",
      "We need to find {V}.",
      "Don't forget, it's {V}.",
      "Write down {V} so you don't forget.",
      "Ask at the desk about {V}.",
      "Check the sign for {V}.",
      "They changed it to {V}.",
      "Remember, it's {V}.",
      "Excuse me, where is {V}?",
    ],
    sports: [
      "The final score was {V}.",
      "At half time it was {V}.",
      "The score is currently {V}.",
      "It finished {V}.",
      "The match ended {V}.",
      "Yesterday's result was {V}.",
      "The game ended {V}.",
      "After extra time it was {V}.",
      "The derby finished {V}.",
      "The result was {V} in the end.",
      "It was {V} after ninety minutes.",
      "The scoreboard showed {V}.",
      "At full time it was {V}.",
      "Can you believe it? {V}!",
      "The final result was {V}.",
    ],
    temperatures: [
      "The forecast says {V} tomorrow.",
      "It's {V} outside.",
      "The temperature dropped to {V}.",
      "Expect {V} this afternoon.",
      "The high today is {V}.",
      "Last night it was {V}.",
      "The thermometer shows {V}.",
      "It will be {V} by evening.",
      "They said it's {V} in the mountains.",
      "The water temperature is {V}.",
      "Right now it's {V}.",
      "Tomorrow morning it will be {V}.",
      "The low tonight is {V}.",
      "It was already {V} at noon.",
      "The weather report says {V}.",
    ],
    large: [
      "The population is {V}.",
      "The total cost is {V} dollars.",
      "We received {V} applications.",
      "The stadium holds {V} people.",
      "They sold {V} copies in the first week.",
      "There are {V} registered users.",
      "The budget is {V} dollars.",
      "About {V} people attended.",
      "The distance is {V} kilometers.",
      "The company has {V} employees.",
      "The city has {V} residents.",
      "We had {V} visitors last month.",
      "The library has {V} books.",
      "Over {V} people signed the petition.",
      "The website gets {V} views per day.",
    ],
  },
  de: {
    cardinals: [
      "Die Antwort ist {V}.",
      "Bitte gehen Sie zu Zimmer {V}.",
      "Es gibt {Vc} Schüler in der Klasse.",
      "Ich brauche {Vc} Kopien dieses Dokuments.",
      "Die Busnummer ist {V}.",
      "Sie hat {Vc} Punkte im Test erreicht.",
      "Wir haben noch {Vc} Tickets übrig.",
      "Schlagen Sie Seite {V} in Ihrem Buch auf.",
      "Er ist heute Morgen {Vc} Kilometer gelaufen.",
      "Ihre Bestellnummer ist {V}.",
      "Im Raum stehen {Vc} Stühle.",
      "Sie hat {Vc} Minuten gewartet.",
      "Das Gebäude hat {Vc} Stockwerke.",
      "Wir brauchen noch {Vc} Freiwillige.",
      "Ich habe {Vc} Vögel auf dem Baum gezählt.",
    ],
    ordinals: [
      "Er wurde {Vpm}.",
      "Das ist das {V} Mal, dass ich frage.",
      "Sie wohnt im {Vobl} Stock.",
      "Heute ist sein {Vsm} Geburtstag.",
      "Wir feiern unseren {Vobl} Jahrestag.",
      "Nehmen Sie die {V} Abzweigung links.",
      "Sie wurde {Vpf} im Rennen.",
      "Das ist die {V} Ausgabe des Buches.",
      "Es ist der {V} Tag des Monats.",
      "Lesen Sie das {V} Kapitel aufmerksam.",
      "Er war die {V} Person, die ankam.",
      "Unser Team belegte den {Vobl} Platz.",
      "Es war ihr {Vsm} Versuch.",
      "Die {V} Frage war die schwerste.",
      "Das ist mein {Vsm} Besuch in dieser Stadt.",
    ],
    years: [
      "Sie wurde {V} geboren.",
      "Das Ereignis fand {V} statt.",
      "Dieses Gebäude wurde {V} erbaut.",
      "Er hat {V} seinen Abschluss gemacht.",
      "Die Firma wurde {V} gegründet.",
      "Das Album erschien {V}.",
      "Dieses Gesetz wurde {V} verabschiedet.",
      "Die Entdeckung wurde {V} gemacht.",
      "Meine Eltern haben {V} geheiratet.",
      "Der Film kam {V} heraus.",
      "Die Erstausgabe wurde {V} gedruckt.",
      "Wir sind {V} in diese Stadt gezogen.",
      "Die Brücke wurde {V} eröffnet.",
      "Dieses Foto wurde {V} aufgenommen.",
      "Die Tradition begann {V}.",
    ],
    decades: [
      "Das geschah {V}.",
      "Der Stil war {V} beliebt.",
      "Musik war {V} anders.",
      "Sie sind {V} aufgewachsen.",
      "Die Mode hat sich {V} stark verändert.",
      "Das war {V} ein verbreiteter Trend.",
      "Die Technik entwickelte sich {V} rasant.",
      "Viele tolle Filme entstanden {V}.",
      "Die Menschen kleideten sich {V} anders.",
      "Dieses Lied war {V} ein Hit.",
      "Die Wirtschaft war {V} stark.",
      "Autos sahen {V} ganz anders aus.",
      "Fernsehen war {V} riesig.",
      "Das Leben war {V} einfacher.",
      "Meine Eltern haben sich {V} kennengelernt.",
    ],
    fractions: [
      "Verwenden Sie {V} des Materials.",
      "Ungefähr {V} der Schüler haben bestanden.",
      "Der Tank ist {V} voll.",
      "Mischen Sie {V} der Zutaten.",
      "Ungefähr {V} der Bevölkerung stimmte zu.",
      "Schneiden Sie es in Stücke und nehmen Sie {V}.",
      "Wir haben {V} des Projekts abgeschlossen.",
      "Nur {V} der Plätze sind belegt.",
      "Sie hat {V} der Pizza gegessen.",
      "Etwa {V} des Budgets wurde ausgegeben.",
      "Die Flasche ist {V} leer.",
      "Er hat gestern Abend {V} des Buches gelesen.",
      "Sie haben {V} der Arbeit bis Mittag erledigt.",
      "Ungefähr {V} der Fläche ist Wald.",
      "Wir haben {V} des verfügbaren Platzes genutzt.",
    ],
    decimals: [
      "Die Messung ergab {V} Zentimeter.",
      "Es wiegt {V} Kilogramm.",
      "Das Ergebnis ist {V}.",
      "Die Anzeige zeigt {V}.",
      "Der Durchschnitt beträgt {V}.",
      "Der pH-Wert ist {V}.",
      "Die Entfernung beträgt {V} Meter.",
      "Die Temperatur lag bei {V} Grad.",
      "Die Geschwindigkeit erreichte {V} Kilometer pro Stunde.",
      "Die Probe ergab {V} Gramm.",
      "Die Spannung beträgt {V} Volt.",
      "Die Höhe beträgt {V} Meter.",
      "Das Verhältnis war {V} zu eins.",
      "Die Konzentration beträgt {V} Milligramm.",
      "Die Dicke beträgt {V} Millimeter.",
    ],
    currencies: [
      "Die Summe beträgt {V}.",
      "Das macht {V} bitte.",
      "Ihr Wechselgeld beträgt {V}.",
      "Der Preis ist {V}.",
      "Ich habe {V} dafür bezahlt.",
      "Es kostet {V} pro Stück.",
      "Die Rechnung betrug {V}.",
      "Sie hat {V} für Lebensmittel ausgegeben.",
      "Der Eintrittspreis beträgt {V}.",
      "Wir haben diesen Monat {V} gespart.",
      "Die Reparatur wird {V} kosten.",
      "Er hat {V} gespendet.",
      "Die Miete beträgt {V} pro Monat.",
      "Ihr Guthaben beträgt {V}.",
      "Die Liefergebühr beträgt {V}.",
    ],
    percentages: [
      "Der Zinssatz beträgt {V}.",
      "Ungefähr {V} der Menschen stimmten zu.",
      "Der Umsatz stieg um {V}.",
      "Die Luftfeuchtigkeit beträgt {V}.",
      "Die Regenwahrscheinlichkeit liegt bei {V}.",
      "Das Ergebnis verbesserte sich um {V}.",
      "Der Akku ist bei {V}.",
      "Die Arbeitslosigkeit sank um {V}.",
      "Das Projekt ist zu {V} abgeschlossen.",
      "Die Wahlbeteiligung lag bei {V}.",
      "Der Rabatt beträgt {V}.",
      "Die Preise stiegen um {V}.",
      "Die Erfolgsquote liegt bei {V}.",
      "Die Anwesenheit erreichte heute {V}.",
      "Der Steuersatz beträgt {V}.",
    ],
    roomBus: [
      "{V} — ist das richtig?",
      "{V} sollte in der Nähe sein.",
      "Merken Sie sich: {V}.",
      "Entschuldigung, wo ist {V}?",
      "Können Sie mir sagen, wo {V} ist?",
      "Wissen Sie, wo {V} ist?",
      "Ich suche {Va}.",
      "Wir müssen {Va} finden.",
      "Haben Sie {Va} gesehen?",
      "Bitte gehen Sie zu {V}.",
      "Vergessen Sie nicht: {V}.",
      "Wir treffen uns in {Vl}.",
      "Ich warte in {Vl}.",
      "Die Besprechung ist in {Vl}.",
      "Fragen Sie an der Rezeption nach {V}.",
    ],
    sports: [
      "Das Endergebnis war {V}.",
      "Zur Halbzeit stand es {V}.",
      "Der Spielstand ist aktuell {V}.",
      "Es endete {V}.",
      "Das Spiel endete {V}.",
      "Das Ergebnis von gestern war {V}.",
      "Die Partie endete {V}.",
      "Nach der Verlängerung stand es {V}.",
      "Das Derby endete {V}.",
      "Am Ende stand es {V}.",
      "Nach neunzig Minuten war es {V}.",
      "Die Anzeigetafel zeigte {V}.",
      "Nach Abpfiff stand es {V}.",
      "Kaum zu glauben: {V}!",
      "Das Endresultat war {V}.",
    ],
    temperatures: [
      "Die Vorhersage sagt {V} für morgen.",
      "Draußen sind es {V}.",
      "Die Temperatur fiel auf {V}.",
      "Erwarten Sie {V} heute Nachmittag.",
      "Der Höchstwert heute ist {V}.",
      "Letzte Nacht waren es {V}.",
      "Das Thermometer zeigt {V}.",
      "Am Abend werden es {V} sein.",
      "In den Bergen soll es {V} sein.",
      "Die Wassertemperatur beträgt {V}.",
      "Gerade sind es {V}.",
      "Morgen früh werden es {V}.",
      "Der Tiefstwert heute Nacht ist {V}.",
      "Mittags waren es schon {V}.",
      "Der Wetterbericht sagt {V}.",
    ],
    large: [
      "Die Bevölkerung beträgt {V}.",
      "Die Gesamtkosten betragen {V} Euro.",
      "Wir haben {V} Bewerbungen erhalten.",
      "Das Stadion fasst {V} Zuschauer.",
      "Sie verkauften {V} Exemplare in der ersten Woche.",
      "Es gibt {V} registrierte Nutzer.",
      "Das Budget beträgt {V} Euro.",
      "Ungefähr {V} Leute nahmen teil.",
      "Die Entfernung beträgt {V} Kilometer.",
      "Das Unternehmen hat {V} Mitarbeiter.",
      "Die Stadt hat {V} Einwohner.",
      "Letzten Monat hatten wir {V} Besucher.",
      "Die Bibliothek hat {V} Bücher.",
      "Über {V} Menschen haben die Petition unterschrieben.",
      "Die Website bekommt {V} Aufrufe pro Tag.",
    ],
  },
  uk: {
    cardinals: [
      "Відповідь — {V}.",
      "Будь ласка, підійдіть до кімнати {V}.",
      "У класі {V} {учень|учні|учнів}.",
      "Мені треба {V:f} {копія|копії|копій} цього документа.",
      "Номер автобуса — {V}.",
      "Вона набрала {V} {бал|бали|балів} на тесті.",
      "У нас є {V} {квиток|квитки|квитків}.",
      "Відкрийте сторінку {V} у підручнику.",
      "Він пробіг {V} {кілометр|кілометри|кілометрів} вранці.",
      "Ваш номер замовлення — {V}.",
      "У кімнаті {V} {стілець|стільці|стільців}.",
      "Час очікування — {V:f} {хвилина|хвилини|хвилин}.",
      "У будівлі {V} {поверх|поверхи|поверхів}.",
      "Нам треба ще {V} {волонтер|волонтери|волонтерів}.",
      "На дереві {V} {птах|птахи|птахів}.",
    ],
    ordinals: [
      "Він фінішував {Vinstr}.",
      "Це {V} раз, коли я питаю.",
      "Сьогодні його {V} день народження.",
      "Візьміть {V} поворот ліворуч.",
      "Сьогодні {V} день місяця.",
      "Уважно прочитайте {V} розділ.",
      "Це мій {V} візит до цього міста.",
      "Наша команда фінішувала {Vfinstr}.",
      "Це була її {Vf} спроба.",
      "Вона прийшла {Vfinstr} у перегонах.",
      "Ми святкуємо нашу {Vfacc} річницю.",
      "Вона живе на {Vl} поверсі.",
      "Це {Vn} видання книги.",
      "Найважчим було {Vn} питання.",
      "Це {Vn} завдання у списку.",
    ],
    years: [
      "Вона народилася у {Vl} році.",
      "Ця подія відбулася у {Vl} році.",
      "Цю будівлю збудовано у {Vl} році.",
      "Він закінчив навчання у {Vl} році.",
      "Компанію засновано у {Vl} році.",
      "Альбом вийшов у {Vl} році.",
      "Цей закон прийняли у {Vl} році.",
      "Відкриття зроблено у {Vl} році.",
      "Мої батьки одружилися у {Vl} році.",
      "Фільм вийшов у {Vl} році.",
      "Перше видання надруковано у {Vl} році.",
      "Ми переїхали до цього міста у {Vl} році.",
      "Міст відкрили у {Vl} році.",
      "Це фото зроблено у {Vl} році.",
      "Ця традиція почалася у {Vl} році.",
    ],
    decades: [
      "Це сталося {V}.",
      "Цей стиль був популярний {V}.",
      "Музика була іншою {V}.",
      "Вони виросли {V}.",
      "Мода сильно змінилася {V}.",
      "Це був поширений тренд {V}.",
      "Технології швидко розвивались {V}.",
      "Багато чудових фільмів знято {V}.",
      "Люди одягалися інакше {V}.",
      "Ця пісня була хітом {V}.",
      "Економіка була сильною {V}.",
      "Автомобілі виглядали зовсім інакше {V}.",
      "Телебачення було величезним {V}.",
      "Життя було простішим {V}.",
      "Мої батьки познайомилися {V}.",
    ],
    fractions: [
      "Додайте {V} склянки борошна.",
      "Приблизно {V} учнів склали іспит.",
      "Бак заповнений на {V}.",
      "Змішайте {V} інгредієнтів.",
      "Приблизно {V} населення погодилось.",
      "Розріжте на шматки і візьміть {V}.",
      "Ми виконали {V} проєкту.",
      "Лише {V} місць зайнято.",
      "Вона з'їла {V} піци.",
      "Приблизно {V} бюджету витрачено.",
      "Пляшка порожня на {V}.",
      "Він прочитав {V} книги вчора ввечері.",
      "До обіду вони зробили {V} роботи.",
      "Приблизно {V} території вкрито лісом.",
      "Ми використали {V} доступного простору.",
    ],
    decimals: [
      "Вимірювання показало {V} сантиметрів.",
      "Це важить {V} кілограмів.",
      "Результат — {V}.",
      "Показник — {V}.",
      "Середнє значення — {V}.",
      "Рівень pH — {V}.",
      "Відстань — {V} метрів.",
      "Температура була {V} градусів.",
      "Швидкість досягла {V} кілометрів на годину.",
      "Зразок показав {V} грамів.",
      "Напруга — {V} вольт.",
      "Висота — {V} метрів.",
      "Співвідношення було {V} до одного.",
      "Концентрація — {V} міліграмів.",
      "Товщина — {V} міліметрів.",
    ],
    currencies: [
      "Загальна сума — {V}.",
      "З вас {V}, будь ласка.",
      "Ваша решта — {V}.",
      "Ціна — {V}.",
      "Я заплатив за це {V}.",
      "Це коштує {V} за штуку.",
      "Рахунок склав {V}.",
      "Вона витратила {V} на продукти.",
      "Вхідний квиток коштує {V}.",
      "Цього місяця ми заощадили {V}.",
      "Ремонт обійдеться у {V}.",
      "Він пожертвував {V} на благодійність.",
      "Оренда — {V} на місяць.",
      "Ваш баланс — {V}.",
      "Вартість доставки — {V}.",
    ],
    percentages: [
      "Відсоткова ставка — {V}.",
      "Приблизно {V} людей погодилось.",
      "Продажі зросли на {V}.",
      "Вологість повітря — {V}.",
      "Імовірність дощу — {V}.",
      "Результат покращився на {V}.",
      "Заряд батареї — {V}.",
      "Безробіття знизилось на {V}.",
      "Проєкт завершено на {V}.",
      "Явка виборців склала {V}.",
      "Знижка — {V}.",
      "Ціни зросли на {V}.",
      "Рівень успішності — {V}.",
      "Відвідуваність сьогодні досягла {V}.",
      "Ставка податку — {V}.",
    ],
    roomBus: [
      "{V} — це правильно?",
      "{V} має бути десь поруч.",
      "Запам'ятайте: {V}.",
      "Підкажіть, де знаходиться {V}?",
      "Я шукаю {Va}.",
      "Вам потрібно знайти {Va}.",
      "Ви бачите {Va}?",
      "Підійдіть до {Vg}.",
      "Ми шукаємо дорогу до {Vg}.",
      "Залишилось кілька метрів до {Vg}.",
      "Зустріч у {Vl}.",
      "Ми будемо в {Vl}.",
      "Чекайте в {Vl}.",
      "Нам треба знайти {Va}.",
      "Ви вже були в {Vl}?",
    ],
    sports: [
      "Фінальний рахунок — {V}.",
      "На перерві було {V}.",
      "Рахунок зараз — {V}.",
      "Матч завершився {V}.",
      "Гра закінчилась {V}.",
      "Вчорашній результат — {V}.",
      "Зустріч закінчилася {V}.",
      "Після додаткового часу стало {V}.",
      "Дербі завершилось {V}.",
      "Зрештою рахунок став {V}.",
      "Після дев'яноста хвилин було {V}.",
      "На табло було {V}.",
      "На фінальному свистку — {V}.",
      "Неймовірно: {V}!",
      "Підсумковий результат — {V}.",
    ],
    temperatures: [
      "Прогноз на завтра — {V}.",
      "На вулиці {V}.",
      "Температура впала до {V}.",
      "Очікується {V} сьогодні вдень.",
      "Максимум сьогодні — {V}.",
      "Вночі було {V}.",
      "Термометр показує {V}.",
      "До вечора буде {V}.",
      "Кажуть, у горах {V}.",
      "Температура води — {V}.",
      "Зараз надворі {V}.",
      "Завтра вранці буде {V}.",
      "Мінімум на сьогоднішню ніч — {V}.",
      "Опівдні вже було {V}.",
      "Прогноз погоди каже {V}.",
    ],
    large: [
      "Населення — {V}.",
      "Загальна вартість — {V}.",
      "Ми отримали {V} заявок.",
      "Стадіон вміщує {V} глядачів.",
      "Вони продали {V} примірників за перший тиждень.",
      "Зареєстровано {V} користувачів.",
      "Бюджет — {V}.",
      "Приблизно {V} людей прийшло.",
      "Відстань — {V} кілометрів.",
      "У компанії {V} працівників.",
      "У місті {V} мешканців.",
      "Минулого місяця було {V} відвідувачів.",
      "У бібліотеці {V} книг.",
      "Понад {V} людей підписали петицію.",
      "Сайт отримує {V} переглядів на день.",
    ],
  },
};

// ── Sentence assembly ──────────────────────────────────────────────────────

/**
 * Get a sentence template for a CategoryValue.
 * Uses learning language for sentence templates.
 * @param {import('./types').CategoryValue} cv
 * @returns {string}
 */
export function getSentence(cv) {
  const cat = cv.mixedCategory || cv.category;
  let templateCat = cat;

  if (cat === 'years' && cv.value && cv.value.isDecade) {
    templateCat = 'decades';
  }

  const langSentences = SENTENCES[lang()] || SENTENCES.en;
  const templates = langSentences[templateCat] || langSentences.cardinals;
  let template = pick(templates);

  // FIX 5: Handle gendered cardinal {V:f} for Ukrainian
  if (lang() === 'uk' && typeof cv.value === 'number' && template.includes('{V:f}')) {
    template = template.replace('{V:f}', cardinalToWords(cv.value, 'f'));
  }

  // FIX 5: Handle noun agreement {form1|form2|form5} for Ukrainian (3 forms)
  if (lang() === 'uk' && typeof cv.value === 'number') {
    template = template.replace(/\{([^{}|]+)\|([^{}|]+)\|([^{}|]+)\}/g, (_match, f1, f2, f5) => {
      const dc = ukDeclensionCase(cv.value);
      if (dc === 1) return f1;
      if (dc === 2) return f2;
      return f5;
    });
  }

  // English noun agreement: {singular|plural} — 2 forms
  if (lang() === 'en' && typeof cv.value === 'number') {
    template = template.replace(/\{([^{}|]+)\|([^{}|]+)\}/g, (_match, singular, plural) => {
      return cv.value === 1 ? singular : plural;
    });
  }

  // Case-aware replacement (Ukrainian/German)
  if (cv.cases) {
    // Order matters: longer placeholders BEFORE shorter to avoid substring corruption
    // E.g. {Vfinstr} before {Vf}, {Vinstr} before {V}, {Vfacc} before {Vf}/{Va}
    return template
      .replace('{Vinstr}', cv.cases.instr || cv.cases.nom || cv.ttsText)
      .replace('{Vfinstr}', cv.cases.finstr || cv.cases.f || cv.ttsText)
      .replace('{Vfacc}', cv.cases.facc || cv.cases.f || cv.ttsText)
      .replace('{Vobl}', cv.cases.obl || cv.cases.nom || cv.ttsText)
      .replace('{Vsm}', cv.cases.sm || cv.cases.nom || cv.ttsText)
      .replace('{Vpm}', cv.cases.pm || cv.cases.nom || cv.ttsText)
      .replace('{Vpf}', cv.cases.pf || cv.cases.nom || cv.ttsText)
      .replace('{Vc}', cv.cases.attr || cv.cases.nom || cv.ttsText)
      .replace('{Vg}', cv.cases.gen || cv.cases.nom || cv.ttsText)
      .replace('{Va}', cv.cases.acc || cv.cases.nom || cv.ttsText)
      .replace('{Vl}', cv.cases.loc || cv.cases.nom || cv.ttsText)
      .replace('{Vf}', cv.cases.f || cv.ttsText)
      .replace('{Vn}', cv.cases.n || cv.ttsText)
      .replace('{V}', cv.cases.nom || cv.ttsText);
  }

  return template.replace('{V}', cv.ttsText);
}
